import type { Product, Review } from "@/types";

export const products: Product[] = [
  {
    id: "1",
    name: "Merino Cashmere Overcoat",
    slug: "merino-cashmere-overcoat",
    description: "Timeless elegance in a luxurious merino-cashmere blend.",
    longDescription:
      "Crafted from the finest merino wool and cashmere blend, this overcoat represents the pinnacle of understated luxury. The structured silhouette and impeccable tailoring make it the cornerstone of any refined wardrobe. Features hand-stitched lapels, satin lining, and subtly weighted hem for perfect drape.",
    price: 895,
    originalPrice: 1200,
    images: [
      "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800",
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800",
      "https://images.unsplash.com/photo-1544441893-675973e31985?w=800",
    ],
    category: "clothing",
    subcategory: "coats",
    tags: ["luxury", "winter", "tailored", "wool"],
    rating: 4.9,
    reviewCount: 128,
    stock: 12,
    sku: "MCO-001",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Camel", hex: "#C19A6B" },
      { name: "Charcoal", hex: "#36454F" },
      { name: "Ivory", hex: "#FFFFF0" },
    ],
    featured: true,
    isNew: false,
    isBestSeller: true,
    materials: ["70% Merino Wool", "30% Cashmere"],
    dimensions: "Length: 110cm",
    weight: "1.2kg",
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Italian Leather Tote",
    slug: "italian-leather-tote",
    description: "Full-grain Italian leather with architectural lines.",
    longDescription:
      "Handcrafted in Florence from full-grain vegetable-tanned leather, this tote develops a unique patina over time. Spacious interior with multiple organization pockets, magnetic closure, and solid brass hardware. The perfect companion from morning meetings to weekend escapes.",
    price: 685,
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800",
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800",
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800",
    ],
    category: "bags",
    subcategory: "totes",
    tags: ["leather", "handcrafted", "italian", "tote"],
    rating: 4.8,
    reviewCount: 89,
    stock: 8,
    sku: "ILT-002",
    colors: [
      { name: "Cognac", hex: "#834333" },
      { name: "Black", hex: "#1a1a1a" },
      { name: "Tan", hex: "#D2B48C" },
    ],
    featured: true,
    isNew: true,
    isBestSeller: false,
    materials: ["Full-grain leather", "Brass hardware"],
    dimensions: "38cm × 28cm × 15cm",
    weight: "0.9kg",
    createdAt: "2024-02-20",
  },
  {
    id: "3",
    name: "Silk Charmeuse Blouse",
    slug: "silk-charmeuse-blouse",
    description: "Fluid silk charmeuse with a relaxed, elegant drape.",
    longDescription:
      "Woven from 22-momme silk charmeuse, this blouse offers an unmatched fluid drape that moves beautifully. The relaxed silhouette works equally well tucked into tailored trousers or left loose over wide-leg pants. Hand-wash cold for best results.",
    price: 320,
    originalPrice: 420,
    images: [
      "https://images.unsplash.com/photo-1594938298603-c8148c4b4466?w=800",
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800",
    ],
    category: "clothing",
    subcategory: "tops",
    tags: ["silk", "luxury", "blouse", "elegant"],
    rating: 4.7,
    reviewCount: 203,
    stock: 25,
    sku: "SCB-003",
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Champagne", hex: "#F7E7CE" },
      { name: "Dusty Rose", hex: "#DCAE96" },
      { name: "Midnight", hex: "#191970" },
    ],
    featured: false,
    isNew: false,
    isBestSeller: true,
    materials: ["100% Silk Charmeuse"],
    createdAt: "2023-11-10",
  },
  {
    id: "4",
    name: "Suede Chelsea Boots",
    slug: "suede-chelsea-boots",
    description: "Hand-lasted suede with Goodyear welt construction.",
    longDescription:
      "These Chelsea boots are crafted using traditional Goodyear welt construction in a small Portuguese atelier. The supple suede upper and cushioned leather insole ensure all-day comfort, while the crepe rubber sole provides grip and longevity.",
    price: 545,
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800",
      "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800",
      "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800",
    ],
    category: "footwear",
    subcategory: "boots",
    tags: ["suede", "chelsea", "handcrafted", "boots"],
    rating: 4.9,
    reviewCount: 156,
    stock: 15,
    sku: "SCB-004",
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44"],
    colors: [
      { name: "Tobacco", hex: "#7B3F00" },
      { name: "Grey", hex: "#808080" },
      { name: "Black", hex: "#1a1a1a" },
    ],
    featured: true,
    isNew: false,
    isBestSeller: true,
    materials: ["Suede upper", "Leather lining", "Crepe rubber sole"],
    createdAt: "2023-09-05",
  },
  {
    id: "5",
    name: "Linen Wide-Leg Trousers",
    slug: "linen-wide-leg-trousers",
    description: "Breathable Belgian linen with a relaxed wide-leg cut.",
    longDescription:
      "Cut from premium Belgian linen, these wide-leg trousers offer effortless sophistication for warm-weather dressing. The high-rise waist and fluid leg create an elongating silhouette, while the natural linen fabric becomes softer and more beautiful with each wear.",
    price: 285,
    images: [
      "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800",
      "https://images.unsplash.com/photo-1594938298603-c8148c4b4466?w=800",
    ],
    category: "clothing",
    subcategory: "pants",
    tags: ["linen", "summer", "wide-leg", "relaxed"],
    rating: 4.6,
    reviewCount: 94,
    stock: 30,
    sku: "LWT-005",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Natural", hex: "#F5F5DC" },
      { name: "Sand", hex: "#C2B280" },
      { name: "White", hex: "#FAFAFA" },
    ],
    featured: false,
    isNew: true,
    isBestSeller: false,
    materials: ["100% Belgian Linen"],
    createdAt: "2024-03-01",
  },
  {
    id: "6",
    name: "Gold Vermeil Hoop Earrings",
    slug: "gold-vermeil-hoop-earrings",
    description: "18k gold vermeil over sterling silver, hand-polished.",
    longDescription:
      "These sculptural hoop earrings are handcrafted in our Brooklyn studio using 18k gold vermeil plating over recycled sterling silver. The organic, slightly irregular form gives them a modern artisanal quality that elevates any outfit.",
    price: 165,
    originalPrice: 210,
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800",
    ],
    category: "jewelry",
    subcategory: "earrings",
    tags: ["gold", "earrings", "handcrafted", "vermeil"],
    rating: 4.8,
    reviewCount: 312,
    stock: 45,
    sku: "GVH-006",
    featured: false,
    isNew: false,
    isBestSeller: true,
    materials: ["18k Gold Vermeil", "Recycled Sterling Silver"],
    createdAt: "2023-07-15",
  },
  {
    id: "7",
    name: "Cashmere Turtleneck Sweater",
    slug: "cashmere-turtleneck-sweater",
    description: "Grade-A Mongolian cashmere in a classic relaxed fit.",
    longDescription:
      "Knitted from Grade-A Mongolian cashmere, this turtleneck sweater is exceptionally soft and insulating without being heavy. The slightly relaxed fit is intentional — it layers beautifully under outerwear while maintaining its shape season after season.",
    price: 420,
    images: [
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800",
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800",
    ],
    category: "clothing",
    subcategory: "knitwear",
    tags: ["cashmere", "sweater", "knitwear", "winter"],
    rating: 4.9,
    reviewCount: 178,
    stock: 20,
    sku: "CTN-007",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Oatmeal", hex: "#DDD5C0" },
      { name: "Sage", hex: "#87A878" },
      { name: "Navy", hex: "#1B2A4A" },
      { name: "Caramel", hex: "#C68B4A" },
    ],
    featured: true,
    isNew: false,
    isBestSeller: true,
    materials: ["100% Grade-A Cashmere"],
    createdAt: "2023-10-20",
  },
  {
    id: "8",
    name: "Structured Wool Blazer",
    slug: "structured-wool-blazer",
    description: "Italian wool with canvassed chest for enduring structure.",
    longDescription:
      "Tailored from Italian wool suiting fabric, this blazer features a hand-padded canvassed chest that molds to your body over time. The single-breasted, two-button design is a timeless silhouette that works from boardrooms to evening events.",
    price: 760,
    images: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800",
      "https://images.unsplash.com/photo-1593032465175-481ac7f401a0?w=800",
    ],
    category: "clothing",
    subcategory: "blazers",
    tags: ["wool", "blazer", "tailored", "italian"],
    rating: 4.8,
    reviewCount: 67,
    stock: 10,
    sku: "SWB-008",
    sizes: ["36", "38", "40", "42", "44", "46"],
    colors: [
      { name: "Charcoal", hex: "#36454F" },
      { name: "Navy", hex: "#1B2A4A" },
      { name: "Cream", hex: "#FFFDD0" },
    ],
    featured: true,
    isNew: true,
    isBestSeller: false,
    materials: ["100% Italian Wool", "Silk lining"],
    createdAt: "2024-01-30",
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    userId: "u1",
    userName: "Alexandra M.",
    productId: "1",
    rating: 5,
    title: "Absolutely worth every penny",
    body: "This coat is extraordinary. The weight, the drape, the craftsmanship — everything is exactly as described. I've worn it daily for three months and it only gets better. People stop me on the street to ask where it's from.",
    helpful: 47,
    verified: true,
    createdAt: "2024-01-20",
  },
  {
    id: "r2",
    userId: "u2",
    userName: "James R.",
    productId: "1",
    rating: 5,
    title: "Exceptional quality, perfect fit",
    body: "Sized up one as suggested and it fits perfectly. The cashmere-merino blend is incredibly soft yet substantial. Worth the investment — this will last decades with proper care.",
    helpful: 32,
    verified: true,
    createdAt: "2024-02-05",
  },
  {
    id: "r3",
    userId: "u3",
    userName: "Sofia L.",
    productId: "2",
    rating: 5,
    title: "The most beautiful bag I own",
    body: "Handcrafted quality is immediately apparent. The leather is already developing a gorgeous patina after just a few weeks. Fits my laptop, daily essentials, and still looks elegant.",
    helpful: 28,
    verified: true,
    createdAt: "2024-03-10",
  },
];

export const categories = [
  { id: "clothing", label: "Clothing", count: 4 },
  { id: "bags", label: "Bags", count: 1 },
  { id: "footwear", label: "Footwear", count: 1 },
  { id: "jewelry", label: "Jewelry", count: 1 },
  { id: "accessories", label: "Accessories", count: 0 },
  { id: "home", label: "Home", count: 0 },
];

export const getFeaturedProducts = () =>
  products.filter((p) => p.featured).slice(0, 4);
export const getNewProducts = () => products.filter((p) => p.isNew);
export const getBestSellers = () => products.filter((p) => p.isBestSeller);
export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug);
export const getProductsByCategory = (category: string) =>
  products.filter((p) => p.category === category);
export const getRelatedProducts = (productId: string, category: string) =>
  products.filter((p) => p.id !== productId && p.category === category).slice(0, 4);
